%
%figXLabel = '';
%figYLabel = '';

set(gcf, 'PaperPositionMode', 'auto');
set(gcf, 'Color', [1 1 1]); % Sets figure background
set(gca, 'Color', [1 1 1]); % Sets axes background
set(gcf, 'Renderer', 'painters');  %
FontSize = 14;%11*1.5;
FontName = 'Helvetica';

%hXLabel = xlabel(figXLabel);
%hYLabel = ylabel(figYLabel);
%hfigs = get(0,'children');
%haxes = findall(gcf,'type','axes');
%h_axLabels = get(haxes,{'XLabel' 'YLabel'});

hXLabel = get(gca,'xLabel'); 
hYLabel = get(gca,'yLabel'); 

set( gca                       , ...
    'FontName'   , FontName );
set(gca,'FontSize',FontSize-1);

set([hXLabel hYLabel], ...
    'FontSize'   , FontSize);

hLegend = get_legend(gcf);
set([hLegend, gca]             , ...
   'FontSize'   , FontSize-1);

set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'ZMinorTick'  , 'on'      , ...
  'XGrid'       , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'ZGrid'       , 'on'      , ...
  'XColor'      , [.0 .0 .0], ...
  'YColor'      , [.0 .0 .0], ...
  'GridLineStyle','--', ...
  'LineWidth'   , 0.75         );


% hLegend = legend(Vars, 'Location', 'northeast','Orientation','vertical');